################################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise1
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.2  2011/09/20 16:44:00  tumbush.tumbush
## Initial check-in.
##
##
###############################################################
CFILES = shift.c
VFILES = shift.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = shift

include ../../Makefiles/DPI/Makefile_DPI
