################################################################################
## Purpose: Makefile for Chap_2_Data_Types/exercise1
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 19:48:04  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/03 22:45:02  Greg
## Updated header
##
###############################################################################


FILES = test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
