################################################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise5_slide
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/09/27 19:50:27  tumbush.tumbush
## Initial check-in
##
##
###############################################################################
CFILES = hello.c
VFILES = hello.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = hello

include ../../Makefiles/DPI/Makefile_DPI


