################################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise8
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/09/27 17:23:22  tumbush.tumbush
## Initial check-in
##
##
###############################################################
CFILES = shift.c
VFILES = shift.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = shift

include ../../Makefiles/DPI/Makefile_DPI
