###########################################################
## Purpose: Makefile for Chap_5_Basic_OOP/homework_solution
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:03:53  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/09 22:26:48  Greg
## Updated to global makefile
##
## Revision 1.1  2011/03/20 19:02:27  Greg
## Initial check in
##
###########################################################

FILES =  my_package.sv my_mem.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI