#################################################################################
## Purpose: Makefile for Chap_7_Threads_and_Interprocess_Communication/exercise1
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:13:41  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/10 23:00:09  Greg
## Initial check-in
##
#################################################################################

FILES = test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
