######################################################
## Purpose: Makefile for Chap_2_Data_Types/exercise11
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 19:48:06  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/05 22:22:55  Greg
## Initial check-in
##
######################################################
FILES = alu.v test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
