########################################################
## Purpose: Makefile for Chap_2_Data_Types/homework1_solution
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 19:48:15  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/04 18:10:43  Greg
## Updated to new global makefile scheme.
##
#########################################################
FILES = my_mem.sv test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
