###############################################################################
## Purpose: Makefile for Chap_4_Connecting_the_Testbench_and_Design/exercise2_3
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 20:22:56  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/08 22:18:18  Greg
## Initial check-in
##
##############################################################################
FILES = test.sv my_reg.sv no_program.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
