########################################################
## Purpose: Makefile for Chap_2_Data_Types/exercise8
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 19:48:13  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/05 22:32:34  Greg
## Initial check-in
##
#########################################################
FILES = test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
