############################################################################
## Purpose: Makefile for Chap_4_Connecting_the_Testbench_and_Design/exercise1
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 20:22:55  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/08 22:13:59  Greg
## Initial check-in
##
############################################################################

FILES = test.sv ahb_master.sv ahb_slave.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI