########################################################################################
## Purpose: Makefile for Chap_7_Threads_and_Interprocess_Communication/homework2_solution
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:13:50  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/11 20:01:18  Greg
## Updated to common Makefile
##
## Revision 1.1  2011/03/19 14:44:10  Greg
## Initial check in
##
########################################################################################

FILES =  test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI