#############################################################################
## Purpose:  Solution for Chap_3_Procedural_Statements_and_Routines/exercise2
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 20:06:44  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/08 20:38:35  Greg
## Initial check-in
##
############################################################################

FILES = test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
