#############################################################
## Purpose: Makefile for Chap10_Advanced_Interfaces/exercise5
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/09/16 21:41:14  tumbush.tumbush
## Moved from exercise7
##
##
##############################################################
FILES = my_package.sv test.sv top.sv 
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
