#####################################################
## Purpose: Makefile for Chap_5_Basic_OOP/exercise6
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:03:49  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/09 13:31:18  Greg
## Initial check-in
##
#####################################################
FILES = my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
