########################################################################################
## Purpose: Makefile for Chap_7_Threads_and_Interprocess_Communication/homework2_problem
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:13:49  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/11 20:00:10  Greg
## Uses common Makefile scheme
##
## Revision 1.1  2011/03/19 14:27:05  Greg
## Initial check in
##
########################################################################################

FILES =  test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI