##############################################################
## Purpose: Makefile for Chap_2_Data_Types/homework2_solution
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 19:48:16  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/04 18:15:54  Greg
## Updated to new global Makefile scheme
##
#########################################################
FILES = my_mem.sv test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
