################################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise1
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/09/27 19:28:34  tumbush.tumbush
## Moved to exercise1_slide
##
## Revision 1.1  2011/05/26 03:20:36  tumbush.tumbush
## Moved repository to cloud
##
## Revision 1.1  2011/05/25 16:34:48  Greg
## Initial check-in
##
###############################################################
CFILES = hello.c
VFILES = hello.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = hello

include ../../Makefiles/DPI/Makefile_DPI
