######################################################################################
## Purpose:  Solution for Chap_3_Procedural_Statements_and_Routines/homework_solution
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 20:06:48  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/08 21:31:35  Greg
## Updated to new 2-file Makefile setup
##
############################################################################

FILES = my_mem.sv test.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI
