######################################################################################
## Purpose: Makefile for Chap_4_Connecting_the_Testbench_and_Design/homework1_solution
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 20:22:58  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/09 02:03:01  Greg
## Updated to use common Makefile
##
## Revision 1.1  2011/03/17 14:29:43  Greg
## Initial check in
##
#######################################################################################

FILES = test.sv my_mem.sv
TOPLEVEL = test

include ../../Makefiles/non_DPI/Makefile_non_DPI