D:\all_code\verilog_module\openMIPS\Code\Chapter4\openmips_min_sopc.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\openmips_min_sopc_tb.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\ex.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\ex_mem.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\id.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\id_ex.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\if_id.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\inst_rom.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\mem.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\mem_wb.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\openmips.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\pc_reg.v
D:\all_code\verilog_module\openMIPS\Code\Chapter4\regfile.v
