########################################################################################
## Purpose: Makefile for Chap10_Advanced_Interfaces/exercise4
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/09/16 21:37:18  tumbush.tumbush
## Moved from exercise5_6
##
##
########################################################################################
FILES = my_package.sv test.sv top.sv 
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
