#########################################################
## Purpose: Makefile for Chap_Randomization/exercise7
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:10:01  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/10 19:19:48  Greg
## Initial check-in
##
#########################################################

FILES = my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
