################################################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise6
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.2  2011/09/27 17:18:00  tumbush.tumbush
## Initial check-in
##
##
###############################################################################
CFILES = shift.cpp
VFILES = shift.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = shift

include Makefile_DPI


