##################################################################################
## Purpose: Makefile for Chap_8_Advanced_OOP_and_Testbench_Guidelines/exercise1_2
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:16:04  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/11 22:36:10  Greg
## Initial check-in
##
##################################################################################
FILES =  my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
