#################################################################
## Purpose: Makefile for Chap_10_Advanced_Interfaces/exercise1_2
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/27 02:45:19  tumbush.tumbush
## Checked into cloud
##
## Revision 1.2  2011/05/15 20:07:47  Greg
## Upgraded to common Makefile
##
## Revision 1.1  2011/05/15 19:56:22  Greg
## Initial check-in
##
#################################################################

FILES = my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI