#################################################################
## Purpose: Makefile for Chap_10_Advanced_Interfaces/exercise3
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/09/16 21:24:10  tumbush.tumbush
## Moved from exercise3_4
##
##
#################################################################

FILES = my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
