##################################################################################
## Purpose: Makefile for Chap_8_Advanced_OOP_and_Testbench_Guidelines/exercise5
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:16:06  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/11 23:01:11  Greg
## Updated to use global make file
##
## Revision 1.1  2011/05/11 22:40:05  Greg
## Initial check-in
##
##################################################################################
FILES =  my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI