################################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise2
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.3  2011/09/24 20:20:26  tumbush.tumbush
## Initial check-in
##
##
###############################################################
CFILES = shift.c
VFILES = shift.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = shift

include ../../Makefiles/DPI/Makefile_DPI
