###############################################################
## Purpose: Makefile for Chap_12_Interfacing_with_C/exercise7
## Author: Greg Tumbush
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/30 19:31:23  tumbush.tumbush
## Checked into cloud repository.
##
###############################################################
CFILES = fib_oa.c
VFILES = test.sv top.sv
FILES = $(VFILES) $(CFILES)
TOPLEVEL = top

include ../../Makefiles/DPI/Makefile_DPI


