######################################################################################
## Purpose: Makefile for Chap_4_Connecting_the_Testbench_and_Design/homework2_solution
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/28 20:22:59  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.2  2011/05/09 02:03:56  Greg
## Updated to use common Makefile
##
## Revision 1.1  2011/03/17 14:08:51  Greg
## Initial check in
##
######################################################################################

FILES = top.sv test.sv my_mem.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI