############################################################################
## Purpose: Makefile for Chap_Randomization/exercise11
## Author: Chris Spear
##
## REVISION HISTORY:
## $Log: Makefile,v $
## Revision 1.1  2011/05/29 19:09:54  tumbush.tumbush
## Check into cloud repository
##
## Revision 1.1  2011/05/10 20:10:55  Greg
## Initial check-in
##
############################################################################

FILES = my_package.sv test.sv top.sv
TOPLEVEL = top

include ../../Makefiles/non_DPI/Makefile_non_DPI
